export const actionTypes = [
  { value: "CREATE_NEW_STAFF_ADMIN", label: "Create New Staff Admin" },
  { value: "CREATE_NEW_STAFF", label: "Create New Staff" },
  { value: "UPDATE_STAFF", label: "Update Staff" },
  { value: "DELETE_STAFF", label: "Delete Staff" },
  { value: "CREATE_NEW_USER", label: "Create New User" },
  { value: "DELETE_USER", label: "Delete User" },
  { value: "RECOVER_USER", label: "Recover User" },
  { value: "UPDATE_USER", label: "Update User" },
  { value: "CREATE_NEW_ADMIN", label: "Create New Admin" },
  { value: "ADMIN_LOGIN", label: "Admin Login" },
  { value: "ADMIN_SET_PASSWORD", label: "Admin Set Password" },
  { value: "STAFF_LOGIN", label: "Staff Login" },
  { value: "STAFF_SET_PASSWORD", label: "Staff Set Password" },
  { value: "CREATE_ORGANIZATION", label: "Create Organization" },
  {
    value: "GET_ORGANIZATION_APP_LEVEL_ENCRYPTION_STATUS_AND_KEY",
    label: "Get Organization App Level Encryption Status and Key",
  },
  {
    value: "SEND_PASSWORD_SET_TOKEN_TO_ADMIN",
    label: "Send Password Set Token to Admin",
  },
  { value: "CREATE_DIVISION", label: "Create Division" },
  { value: "COMPLETE_MFA_LOGIN", label: "Complete MFA Login" },
  { value: "CREATE_NEW_API_KEY", label: "Create New API Key" },
  { value: "DELETE_API_KEY", label: "Delete API Key" },
  { value: "PATCH_API_KEY_STATUS", label: "Patch API Key Status" },
  { value: "CREATE_ROLE", label: "Create Role" },
  { value: "CREATE_GROUP", label: "Create Group" },
  { value: "CREATE_PERMISSION", label: "Create Permission" },
  { value: "ASSIGN_ROLE_TO_GROUP", label: "Assign Role to Group" },
  { value: "UPDATE_ROLE", label: "Update Role" },
  { value: "DELETE_ROLE", label: "Delete Role" },
  { value: "CREATE_ELEMENT", label: "Create Element" },
  { value: "UPDATE_ELEMENT", label: "Update Element" },
  {
    value: "ADD_VERIFICATIONS_TO_ELEMENT",
    label: "Add Verifications to Element",
  },
  {
    value: "REMOVE_VERIFICATIONS_FROM_ELEMENT",
    label: "Remove Verifications from Element",
  },
  { value: "CREATE_FORM", label: "Create Form" },
  { value: "UPDATE_FORM", label: "Update Form" },
  { value: "ADD_COUNTRIES_TO_FORM", label: "Add Countries to Form" },
  { value: "REMOVE_COUNTRIES_FROM_FORM", label: "Remove Countries from Form" },
  { value: "CREATE_PRICING", label: "Create Pricing" },
  { value: "UPDATE_PRICING", label: "Update Pricing" },
  { value: "CREATE_VERIFICATION", label: "Create Verification" },
  { value: "UPDATE_VERIFICATION", label: "Update Verification" },
  {
    value: "ADD_COUNTRIES_TO_VERIFICATION",
    label: "Add Countries to Verification",
  },
  {
    value: "REMOVE_COUNTRIES_FROM_VERIFICATION",
    label: "Remove Countries from Verification",
  },
  { value: "CREATE_PROVIDER", label: "Create Provider" },
  { value: "UPDATE_PROVIDER", label: "Update Provider" },
  { value: "CREATE_WORKFLOW", label: "Create Workflow" },
  { value: "UPDATE_WORKFLOW", label: "Update Workflow" },
  { value: "DELETE_WORKFLOW", label: "Delete Workflow" },
  { value: "TOGGLE_ORG_SETTINGS", label: "Toggle Org Settings" },
  { value: "CHANGE_STAFF_PASSWORD", label: "Change Staff Password" },
  { value: "UPDATE_STAFF_PROFILE", label: "Update Staff Profile" },
  { value: "UPDATE_STAFF_BY_ADMIN", label: "Update Staff by Admin" },
];

export const chartColors = ["#0088FE", "#00C49F", "#FFBB28", "#FF8042"];
