#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running Prettier..."
npm run format 

echo "Running ESLint..."
npm run lint || { echo "ESLint failed. Fix the linting issues."; exit 1; }


echo "Running Tests..."
npm run test || { echo "Tests failed. Fix the test issues."; exit 1; }
