name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  BUILD:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repositiory
        uses: actions/checkout@v4
        with:
          repository: sourceidtechorg/sid-admin-dashboard
      - name: Build docker image
        id: build-image
        run: |
          docker build -t admin-dashboard:latest .

  BUILD_AND_PUSH:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repositiory
        uses: actions/checkout@v4
        with:
          repository: sourceidtechorg/sid-admin-dashboard
      - name: Set Package Version
        id: IMAGE_TAG
        run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ECR_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sid-admin-dashboard
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:${{ steps.IMAGE_TAG.outputs.PACKAGE_VERSION }} -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:${{ steps.IMAGE_TAG.outputs.PACKAGE_VERSION }}
          docker push $REGISTRY/$REPOSITORY:latest
